[package]
name = "day14part2"
version = "0.1.0"
authors = ["Chirag Jain"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
